services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/Shahg333/n8n-render
    plan: free
    envVars:
      - key: N8N_AUTH_MODE
        value: email
      - key: N8N_EMAIL_MODE_USER_EMAIL
        value: shah.alamgir333@gmail.com
      - key: N8N_EMAIL_MODE_USER_PASSWORD
        value: Ezza@alam786786
      - key: N8N_HOST
        value: n8n.ezetrends.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.ezetrends.com

