services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/Shahg333/n8n-render
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Ezza@alam786786
      - key: N8N_HOST
        value: n8n-render.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-render.onrender.com
